apiVersion: apps/v1
kind: Replicaset
metadata:
  name: meureplicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template: 
    metadata:
      labels: 
        app: web
    spec:
      containers:
      - name: site
        image: lzocateli/web-page:blue
        ports:
        - containerPorts: 80